[package]
name = "nihav"
version = "0.1.0"
authors = ["Kostya Shishkov <kostya.shishkov@gmail.com>"]

[dependencies]
bitflags = "0.5.0"

[features]
default = ["all_decoders", "all_demuxers"]
demuxers = []
all_demuxers = ["demuxer_avi", "demuxer_gdv"]
demuxer_avi = ["demuxers"]
demuxer_gdv = ["demuxers"]

decoders = []
all_decoders = ["all_video_decoders", "all_audio_decoders"]

all_video_decoders = ["decoder_indeo2", "decoder_indeo3"]
decoder_indeo2 = ["decoders"]
decoder_indeo3 = ["decoders"]

all_audio_decoders = ["decoder_pcm"]
decoder_pcm = ["decoders"]
